version: '3.3'
services:
    gpu-alert:
        build:
            dockerfile: Dockerfile
        volumes:
            - './data:/app/data'
            - './config:/app/config'
        restart: always
        image: 'gpu-alert:latest'
